
const message = {
   VAL_FAILED: "validation failed",
   SUCCESS_RES: "successful",
   NOT_FOUND: "data not found",
   ERROR_OCCURRED: "An error occurred",
   SUCCESSFULLY_UPDATED: "Successfully updated",
   SUCCESSFULLY_ADDED: "Data added successfully",
   DELETE_SUCCESS: "Deleted successfully",
   DATA_NOT_FOUND: "Data is not found",
   INVALID_ID: "invalid id",
   INVALID_GENDER: "invalid gender",
   INVALID_NAME: "invalid name",
   SUCCESSFULLY_REGISTERED: "Data Register Successfully",
   INTERNAL_SERVER_ERROR: "Internal Server Error",
   LOGIN_SUCCESSFUL: "Login SuccessFul",
   UNAUTHORIZED: "UnAuthorized",
   INVALID_TOKEN: "Invalid Token",
   TOKEN_EXPIRED_ERROR: "Token is Expired",
   INVALID_EMAIL: "Invalid Email Id",
   INVALID_PASSWORD: "Invalid Password",
   INVALID: "invalid data",
   SUCCESSFUL: "successful",
   NO_FILES_UPLOADED: "No files were uploaded.",
   INVALID_IMAGE_ID: "Invalid imageId",
   IMAGE_DELETED_SUCCESSFULLY: "Image Deleted Successfully",
   USER_ALREADY_EXISTS: "User Already Exists",
   SOMETHING_WENT_WRONG: "Something went wrong",
   USER_NOT_FOUND: "User Not Found",
   INVALID_USER_ID: "Invalid User Id",
   IMAGE_NOT_FOUND: "Image Not Found",
   INVALID_USER_NAME: "Invalid User Name",
   POST_IS_REQUIRED: "Post is Required",
   POST_NOT_FOUND: "Post not found",
   INVALID_POST_ID: "Invalide Post Id",
   INVALID_COMMENT: "Invalid Comment",
   INVALID_COMMENT_ID: "Invalide Comment Id",
   INVALID_REPLY_COMMENT_ID: "Invlid Reply Comment Id",
   COMMENT_CREATED_SUCCESSFULLY: "Comment Created Successfully",
   COMMENT_NOT_FOUND: "Comment not found",
   COMMENT_UPDATED_SUCCESSFULLY: "Comment updated Successfully",
   COMMENT_DELETED_SUCCESSFULLY: "Comment Deleted Successfully",
   COMMENT_REPLY_CREATED_SUCCESSFULLY: "Comment Reply Created successfully",
   COMMENT_REPLY_NOT_FOUND: "Comment Reply not found",
   COMMENT_REPLY_UPDATED_SUCCESSFULLY: "Comment Reply Updated Successfully",
   COMMENT_REPLY_DELETED_SUCCESSFULLY: "Comment Reply deleted Successfully",
   POST_CREATED_SUCCESSFULLY: "Post Created Successfully",
   INVALID_DESCRIPTION: "Invalid Description",
   POST_DELETED_SUCCESSFULLY: "Post Deleted Successfully",
   INVALID_COMMENT_REPLY_ID: "Invalid Comment Reply Id",
   PROFILE_PICTURE_IS_REQUIRED: "Profile Picture is required"
}

export default message;